production:
  adapter: postgresql
  database: xrono_production
  username: postgres

development:
  adapter: postgresql
  database: xrono_development
  username: postgres

test: &test
  adapter: postgresql
  database: xrono_test
  username: postgres

cucumber:
  <<: *test
