production:
  adapter: postgresql
  database: xrono_production

development:
  adapter: postgresql
  database: xrono_development

test: &test
  adapter: postgresql
  database: xrono_test

cucumber:
  <<: *test
